services:
  - type: web
    name: hannah-messaging-app
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci --include=dev && npx tsc -b && npx vite build && cd server && npm install
    startCommand: cd server && node server.js
    healthCheckPath: /api/health
    healthCheckTimeout: 10
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: API_KEY
        value: "4026"
